### ISSUE TITLE
E700: Unknown function: ... (Vim 8.2)

### ISSUE THREAD

**Issue by kertahayu** [noahfrederick/vim-laravel#20]
I installed using vundle.
```
Plugin 'tpope/vim-dispatch'             "| Optional
Plugin 'tpope/vim-projectionist'        "|
Plugin 'noahfrederick/vim-composer'     "|
Plugin 'noahfrederick/vim-laravel'
```

when I open vim this red message appears.
```
Error detected while processing VimEnter Autocommands for "*"..function ProjectionistDetect[43]..VimEnter Autocommands for "*"..function ProjectionistDetect[40]..User Autocommands for "ProjectionistDetect"..function <SNR>56_projectionist_detect[2]..script /Users/dele/.vim/bundle/vim-composer/autoload/composer.vim[144]..function <SNR>100_add_methods[2]..<SNR>100_function:
line    1:
E700: Unknown function: <SNR>56_project_path
Press ENTER or type command to continue
Error detected while processing VimEnter Autocomman
```

all vim-laravel features don't work.

my vim version :
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  4 2020 16:40:08)
macOS version
Included patches: 1-1800
```

**Comment by noahfrederick** [comment]
Thanks for the report. This appears to have been caused by a recent change in Vim.

As far as I can tell from the error message, `expand('<sfile>')` in script number 100 (`autoload/composer.vim`) is producing a script number of 56, which is actually `plugin/composer.vim`, where the calling autocommand is registered.

I see that there are at least a couple patches in the Vim 8.2 series that touch `<sfile>`, which may have broken this functionality.

I'll see if I can find a workaround. Meanwhile, Vim 8.1 or earlier, or Neovim should work.

**Comment by noahfrederick** [comment]
@dele-corporate Please update to the latest versions of *both* composer.vim and laravel.vim, and that should take care of the issue.
