### ISSUE TITLE
Gnome Terminal not working

### ISSUE THREAD

**Issue by devbapidey** [noahfrederick/vim-laravel#25]
I want to run :Artisan serve in background. I am using gnome terminal. How to I archive it. I don't know how tpope/vim-dispatch work. Can you pls help me on it.

**Comment by devbapidey** [comment]
I didn't try it on tmax.

**Comment by noahfrederick** [comment]
So what happens when you do `:Start`?

**Comment by devbapidey** [comment]
![Screenshot from 2021-07-08 08-09-59](https://user-images.githubusercontent.com/33697097/124853735-02e3ce00-dfc4-11eb-8f44-c2a3faf95be8.png) This is picture. Now how to return code editing. **Ctrl+w+w** not working.

**Comment by noahfrederick** [comment]
> I don't know how tpope/vim-dispatch work.

As far as I know, it requires Tmux or GNU Screen to run tasks in a non-blocking way. It doesn't integrate with Gnome Terminal in any special way. Since you're not using those, I suggest simply opening a new terminal tab and running `php artisan serve` at the command line instead of relying on `:Start`. You might also want to try `:Start!` instead, which is supposed to start the task in the background. I'm not sure if that will work for you, though.

**Comment by devbapidey** [comment]
I try ed tmux. But it's not working as I wish.
